# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/davidalves/Desktop/2Semestre/CG/CG25-26

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/davidalves/Desktop/2Semestre/CG/CG25-26

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davidalves/Desktop/2Semestre/CG/CG25-26/CMakeFiles /Users/davidalves/Desktop/2Semestre/CG/CG25-26//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davidalves/Desktop/2Semestre/CG/CG25-26/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generator

# Build rule for target.
generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generator
.PHONY : generator

# fast build rule for target.
generator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/build
.PHONY : generator/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

TinyXML/tinyxml2.o: TinyXML/tinyxml2.cpp.o
.PHONY : TinyXML/tinyxml2.o

# target to build an object file
TinyXML/tinyxml2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/TinyXML/tinyxml2.cpp.o
.PHONY : TinyXML/tinyxml2.cpp.o

TinyXML/tinyxml2.i: TinyXML/tinyxml2.cpp.i
.PHONY : TinyXML/tinyxml2.i

# target to preprocess a source file
TinyXML/tinyxml2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/TinyXML/tinyxml2.cpp.i
.PHONY : TinyXML/tinyxml2.cpp.i

TinyXML/tinyxml2.s: TinyXML/tinyxml2.cpp.s
.PHONY : TinyXML/tinyxml2.s

# target to generate assembly for a file
TinyXML/tinyxml2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/TinyXML/tinyxml2.cpp.s
.PHONY : TinyXML/tinyxml2.cpp.s

catmull.o: catmull.cpp.o
.PHONY : catmull.o

# target to build an object file
catmull.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/catmull.cpp.o
.PHONY : catmull.cpp.o

catmull.i: catmull.cpp.i
.PHONY : catmull.i

# target to preprocess a source file
catmull.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/catmull.cpp.i
.PHONY : catmull.cpp.i

catmull.s: catmull.cpp.s
.PHONY : catmull.s

# target to generate assembly for a file
catmull.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/catmull.cpp.s
.PHONY : catmull.cpp.s

engine.o: engine.cpp.o
.PHONY : engine.o

# target to build an object file
engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cpp.o
.PHONY : engine.cpp.o

engine.i: engine.cpp.i
.PHONY : engine.i

# target to preprocess a source file
engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cpp.i
.PHONY : engine.cpp.i

engine.s: engine.cpp.s
.PHONY : engine.s

# target to generate assembly for a file
engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cpp.s
.PHONY : engine.cpp.s

generator.o: generator.cpp.o
.PHONY : generator.o

# target to build an object file
generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/generator.cpp.o
.PHONY : generator.cpp.o

generator.i: generator.cpp.i
.PHONY : generator.i

# target to preprocess a source file
generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/generator.cpp.i
.PHONY : generator.cpp.i

generator.s: generator.cpp.s
.PHONY : generator.s

# target to generate assembly for a file
generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator.dir/build.make CMakeFiles/generator.dir/generator.cpp.s
.PHONY : generator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... engine"
	@echo "... generator"
	@echo "... TinyXML/tinyxml2.o"
	@echo "... TinyXML/tinyxml2.i"
	@echo "... TinyXML/tinyxml2.s"
	@echo "... catmull.o"
	@echo "... catmull.i"
	@echo "... catmull.s"
	@echo "... engine.o"
	@echo "... engine.i"
	@echo "... engine.s"
	@echo "... generator.o"
	@echo "... generator.i"
	@echo "... generator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

